project:
  type: website

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    html-math-method: mathjax # to render \slashed
    code-fold: true
    highlight-style: github
    css: styles.css
    callout-appearance: default  # Enables callouts like [!NOTE]

metadata-files:
  - _metadata.yml
