project:
  type: website

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    html-math-method: katex
    code-fold: true
    highlight-style: github
    css: styles.css
    callout-appearance: simple
    lang: en
    citation-location: margin
    pandoc-args:
      - --number-offset=0

metadata-files:
  - _metadata.yml
